### ISSUE TITLE
Monitor模块有什么用？

### ISSUE THREAD

**Issue by ziXiong** [lyyyuna/wechat_robot#10]
看代码，monitor会在各个queue的长度超过3时自动删除值，这样做岂不是会漏掉消息？
把monitor删掉之后，微信机器人也能正常使用。

所以，monitor设置着有什么其他目的吗？

**Comment by lyyyuna** [comment]
@ziXiong 
机器人发送太频繁会被腾讯禁掉。当时我用这个作一下限制，以防某一时刻对话量激增。

后来我又在发送函数那加了延时，所以理论上更不会发太频繁。但要是某个群聊天人数太多，机器人对那个群的回复会滞后很多（因为延时），别人看到会很突兀，反正只是娱乐用的机器人，干脆就当队列太长时把消息删了。。。

**Comment by ziXiong** [comment]
@lyyyuna 多谢回答~
