### ISSUE TITLE
可否考虑整理一份pip requirements

### ISSUE THREAD

**Issue by ghost** [lyyyuna/wechat_robot#12]
Hi, nice work!
但是我对python不是很熟, 可否考虑整理一份pip 的requirements管理依赖?

**Comment by lyyyuna** [comment]
@pixyonly 
Hi, 需要 > Python 3.5，应该只依赖于 aiohttp 库。还需要的话我会整理。

**Comment by pixyonly** [comment]
了解

**Comment by ghost** [comment]
了解
